spring:
  application:
    name: java
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#    jpa:
#      hibernate:
#        ddl-auto: none
#      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
#      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}
      uri: mongodb+srv://hoangvanquoc923:movieapp123@cluster0.icsie.mongodb.net/movieapp