spring:
  application:
    name: java
  data:
    mongodb:
#      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}
      uri: mongodb+srv://hoangvanquoc923:movieapp123@cluster0.icsie.mongodb.net/movieapp

openai:
  api:
    key: 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